### PR TITLE
Add support of Swift Package Manager

### PR DESCRIPTION
**Pull request by ale-zai**
When and if this PR will be accepted, you need to:
- Create new release x.x.x
- Attach Pia.xcframework.zip to this newly created release
- Remove Pia.xcframework.zip from git
- Update URL of framework archive in package manifest. For now it points to the latest version of Pia.xcframework.zip in master branch
- Update installation section in README

### CODE REVIEW

**Comment by mariusc** [comment]
Hi @Miss-PiA, are there plans to add support for Swift Package Manager? 

The fork from @ale-zai worked well for us, but since it's a fork, it needs to be updated from upstream whenever you push new commits to this repo, and that is quite cumbersome. It would be great if Netaxept added support for SPM. 

Alternatively, would it be possible for you @ale-zai to update your fork from upstream?

**Comment by ale-zai** [comment]
@mariusc, I updated package, so you can use it if's still actual for you (:
I'm curious why @Miss-PiA don't want to add support of package manager.

**Comment by Miss-PiA** [comment]
Hi @ale-zai  and @mariusc,

Many thanks for your great contribution for our project! 

Swift package manager(SPM) is definitely a good appoarch for iOS SDK integration which is on our radar. Since we are at full speed developing a new generation SDK v.3 which has already planned to distribute through SPM as binary dependency, we will get back to you when we can scope SPM support for current v.2. We can keep you posted whenever we have clear timeline to get it supported!
 
 Really appreciated and welcomed for all your support to make our SDK in a better shape!

**Comment by Miss-PiA** [comment]
We have added SPM support along with latest 2.7.3 release. We are closing this PR and thank you for your contribution

**Pull request closed without merging**
